### PR TITLE
update fallback list with https://botblock.org/api/lists

### PR DESCRIPTION
**Pull request by DonovanDMC**

### CODE REVIEW

**Comment by advaith1** [comment]
Did you manually edit it or copy all the data from botblock? Since there are probably other outdated parts

**Comment by DonovanDMC** [comment]
manually, I looked at the list url and there's a lot of outdated stuff

**Comment by DonovanDMC** [comment]
https://botblock.org/api/lists

**Comment by DonovanDMC** [comment]
@advaith1 changed it to the full list

**Comment by DonovanDMC** [comment]
If it wouldn't post when the list is successfully pulled people likely won't provide the token so it would be useless in most cases

**Comment by MattIPv4** [comment]
@DonovanDMC Well afaik @T0TProduction has specified it in the docs for this lib as a list that works for here, so probably best to leave it in the fallback data so that it does indeed work.

**Comment by advaith1** [comment]
It currently does post to DBL so I'm not exactly sure how this will affect that

**Comment by MattIPv4** [comment]
@advaith1 yeah currently the lib has the fallback data for dbl and so does post, this PR would remove that fallback data and do dbl would no longer work as botblock doesn't support it.

**Comment by advaith1** [comment]
Oh I didn't look at the recent changes that closely, so it manually gets DBL data from the fallback even if it successfully gets the data from botblock?

**Comment by MattIPv4** [comment]
@advaith1 dbl data isn't on botblock, so it relies on the fallback for it and manually posts to dbl.

**Comment by T0TProduction** [comment]
included in another pull requests bc i first made some changes

**Pull request closed without merging**
