### PR TITLE
Remove boatlist.ml, it seems to be dead and isnt on BotBlock

### PR DESCRIPTION
**Pull request by advaith1**

### CODE REVIEW

**Comment by MattIPv4** [comment]
Please see the notice attached on https://botblock.org/lists/boatlist.ml
The list has been hidden per the request of the owner and is not shut down.
The endpoint https://botblock.org/api/lists reveals all lists currently supported on the API, hidden or not.

**Comment by advaith1** [comment]
The boatlist.ml website doesnt seem to be in use thought...

**Comment by MattIPv4** [comment]
As far as I know, the owners of the list are sorting out issues with their domain. The list is still on BotBlock currently and so by extension I would assume @T0TProduction would agree it should be here. This wrapper would load in the data from BotBlock if it wasn't manually in the lib anyway afaik.

**Comment by advaith1** [comment]
ok

**Comment by MattIPv4** [comment]
@advaith1 / @T0TProduction Might be worth re-opening this, as stated on https://botblock.org/lists/boatlist.ml the list has now shut down.

**Comment by advaith1** [comment]
Wouldn't it be better to just copy over all of botblock's current data?

**Comment by MattIPv4** [comment]
Probably yes

**Comment by T0TProduction** [comment]
That's what i was planning on doing 👌🏻

**Comment by advaith1** [comment]
#18

**Pull request closed without merging**
