### PR TITLE
ls.terminal.ink has been renamed to discordapps.dev

### PR DESCRIPTION
**Pull request by 7coil**

### CODE REVIEW

**Comment by 7coil** [comment]
This will break compatibility with people who are posting to `ls.terminal.ink` when they want to update `discordapps.dev`.

Maybe if `ls.terminal.ink` could be an alias, that would be excellent

**Comment by advaith1** [comment]
The fallbacklistdata is just a copy of https://botblock.org/api/lists, used when BotBlock cannot be reached.

**Comment by MattIPv4** [comment]
@advaith1 With DBL manually injected. But yeah, this data is only ever used when BotBlock fails.

**Comment by T0TProduction** [comment]
Yeah, it's just a fallback (as the name suggests), but let's keep it up to date as much as we can.

**Pull request merged**
