### PR TITLE
Fixed DBL-issue (and changed AUTHORS website of myself)

### PR DESCRIPTION
**Pull request by gleeny**

### CODE REVIEW

**Comment by T0TProduction** [comment]
Should it really be null? Is their doc outdated or does the problem maybe come from something else
image

**Comment by gleeny** [comment]
I would assume since their official DBLAPI-package doesn't use shards that it might be glitched somehow.



I'll do more testing...

**Comment by gleeny** [comment]
Okay, quick update. I've been doing some testing on a bot with two shards and this is the information I've gathered;

Shard 0 sends all the information with `server_count`, `shards` and `shard_count`.


Shard 1 sends only `server_count` from that shard, as if this shard's bot was not sharded at all.


Since shard 1 comes online after shard 0, it will overwrite DiscordBots.org's data (and maybe other bot lists' data as well)
I currently do not have time to fix this issue, but I am able to work on a fix tomorrow.

**Comment by gleeny** [comment]
Long time no see, I've been busy the last week. I think I've come up with a fix, currently testing it.

**Comment by T0TProduction** [comment]
I've commented on the changes you made on your fork, i think you've found and solved the problem, though some additions seemed unnecessary to me

**Comment by gleeny** [comment]
Long time no see - again. I've fixed the issue now, https://github.com/gleeny/BLAPI. Also noticed I'm not sending to the branch this is associated with, so currently moving stuff over to the patch-1 branch.

**Pull request merged**
